# Numpy
It has functions for working in domain of linear algebra, fourier transform, and matrices.
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

In [1]:
import numpy as np

In [7]:
# One way to initialize an array is using a Python sequence
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [8]:
# 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
# Create an array with 5 dimensions 
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# Array attributes

In [10]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [11]:
a.ndim

2

In [12]:
a.shape

(3, 4)

In [13]:
a.size

12

In [14]:
import math
a.size == math.prod(a.shape)

True

In [15]:
a.dtype

dtype('int64')

# Array Creation

In [16]:
np.zeros(2)

array([0., 0.])

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [7]:
np.empty(2)

array([0.00000000e+000, 1.01713625e-311])

In [8]:
np.arange(4)

array([0, 1, 2, 3])

In [9]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [10]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [120]:
np.random.seed(0)  # Ensures reproducibility of random numbers
random_matrix = np.random.randint(10, 100, size=(3, 3))  # Create a 3x3 matrix of random integers between 10 and 100
random_matrix

array([[54, 57, 74],
       [77, 77, 19],
       [93, 31, 46]], dtype=int32)

In [122]:
i= np.eye(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Array Indexing, Reshaping and Slicing

In [50]:
arr = np.array([1, 2, 3, 4])

arr[0]

np.int64(1)

In [51]:
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [52]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr[0, 1] #2nd element on 1st row:

np.int64(2)

In [53]:
arr[0][1]

np.int64(2)

In [54]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr[0, 1, 2]

np.int64(6)

In [55]:
#  reshape an array
a = np.arange(6)
a.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [57]:
# np.newaxis will increase the dimensions of your array by one dimension when used once.
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
a2 = a[np.newaxis, :]
a2.shape

(6,)


(1, 6)

In [58]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [59]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
col_vector

(6, 1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [60]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [61]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [64]:
# ou do not have to specify an exact number for one of the dimensions in the reshape method. byPass -1 as the value
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2,-1)
newarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [65]:
# Flattening array 
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
newarr

array([1, 2, 3, 4, 5, 6])

In [66]:
data = np.array([1, 2, 3])
data[1]

np.int64(2)

In [67]:
data[0:2]

array([1, 2])

In [68]:
data[1:]

array([2, 3])

In [69]:
# Return every other element from index 1 to index 5
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[1:5:2]

array([2, 4])

In [70]:
arr[::2]

array([1, 3, 5, 7])

In [71]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[a < 5] #print all of the values in the array that are less than 5

array([1, 2, 3, 4])

In [72]:
# From the second element, slice elements from index 1 to index 4 (not included)
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [73]:
divisible_by_2 = a[a%2==0]
divisible_by_2 

array([ 2,  4,  6,  8, 10, 12])

In [74]:
# use np.nonzero() to print the indices of elements that are
b = np.nonzero(a < 5)
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [75]:
# Change data type from float to integer by using 'i' as parameter valu
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [76]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [77]:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [78]:
# copy func
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [79]:
# view func
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [80]:
# to check if an array owns its own data
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


# Iterating Arrays

In [81]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [82]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [83]:
# Iterate on each scalar element of the 2-D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [83]:
# nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [88]:
# Iterating With Different Step Size
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [89]:
# Enumeration means mentioning sequence number of somethings one by one
# Enumerate on following 1D arrays elements
arr = np.array([5, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 5
(1,) 2
(2,) 3


In [90]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# NumPy Joining Array

In [92]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [94]:
# Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)
arr

array([[1, 4],
       [2, 5],
       [3, 6]])

In [95]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
# sorting
np.sort(arr)



array([1, 2, 3, 4, 5, 6, 7, 8])

In [96]:
# Correctly create the NumPy array
a = np.array([
    [5, 2, 2, 65],
    [2, 3, 6, 70],
    [9, 1, 0, 13]
])

np.argsort(a, axis=-1) #eturn the indices that would sort each row of the array

array([[1, 2, 0, 3],
       [0, 1, 2, 3],
       [2, 1, 0, 3]])

In [97]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [98]:
a= np.arange(8)
a.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [99]:
# hstack() to stack along rows.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [101]:
# vstack()  to stack along columns.
arr = np.vstack((arr1, arr2))
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
# dstack() to stack along height, which is the same as depth.
arr = np.dstack((arr1, arr2))
arr

array([[[1, 4],
        [2, 5],
        [3, 6]]])

# Splitting Array

In [105]:
# Split the array in 3 parts
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
# The return value is a list containing three arrays.
newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [107]:
# Split Into Arrays
# array_split() method is an array containing each of the split as an array.
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

newarr
# the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [110]:
# Split the 2-D array into three 2-D arrays.
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
newarr

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

# Searching Arrays

In [111]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
np.where(arr == 4)

(array([3, 5, 6]),)

In [112]:
np.where(arr%2 == 0)

(array([1, 3, 5, 6]),)

In [114]:
"""There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

The searchsorted() method is assumed to be used on sorted arrays."""
arr = np.array([6, 7, 8, 9])
np.searchsorted(arr, 7)


np.int64(1)

In [116]:
# Find the indexes where the values 2, 4, and 6 should be inserted:
arr = np.array([1, 3, 5, 7])
np.searchsorted(arr, [2, 4, 6])

array([1, 2, 3])

# Mathematical and Statistical Operations

In [132]:
arr = np.random.rand(5, 5)
arr

array([[0.91823547, 0.21682214, 0.56518887, 0.86510256, 0.50896896],
       [0.91672295, 0.92115761, 0.08311249, 0.27771856, 0.0093567 ],
       [0.84234208, 0.64717414, 0.84138612, 0.26473016, 0.39782075],
       [0.55282148, 0.16494046, 0.36980809, 0.14644176, 0.56961841],
       [0.70373728, 0.28847644, 0.43328806, 0.75610669, 0.39609828]])

In [133]:
np.sum(arr)

np.float64(12.657176520825619)

In [134]:
np.mean(arr) # Compute the mean of the matrix

np.float64(0.5062870608330248)

In [135]:
np.max(arr)# Find the maximum value in the matrix

np.float64(0.9211576102371998)

In [136]:
np.min(arr)  # Find the minimum value in the matrix

np.float64(0.009356704856532616)

In [137]:
row_sums = np.sum(matrix, axis=1)  # Sum the elements along rows
col_sums = np.sum(matrix, axis=0)  # Sum the elements along columns

print("Row-wise sums:", row_sums)
print("Column-wise sums:", col_sums)

Row-wise sums: [2.43243414 3.38239747 3.16021584 1.47819687 3.3890618 ]
Column-wise sums: [2.75938539 1.76957558 2.85875536 3.25367501 3.20091476]


In [138]:
cumsum_rows = np.cumsum(matrix, axis=1)  # Compute the cumulative sum along each row
cumprod_cols = np.cumprod(matrix, axis=0)  # Compute the cumulative product along each column

print( cumsum_rows)
print(cumprod_cols)

[[0.58185033 0.99621892 1.47091642 2.09442652 2.43243414]
 [0.67475232 0.99195406 1.77029955 2.7198706  3.38239747]
 [0.01357164 0.63641773 1.31007736 2.28202236 3.16021584]
 [0.50962438 0.56533907 1.01649828 1.03648595 1.47819687]
 [0.97958673 1.33903119 1.81992472 2.50858591 3.3890618 ]]
[[0.58185033 0.41436859 0.4746975  0.6235101  0.33800761]
 [0.39260486 0.13143844 0.36947866 0.59206714 0.22393913]
 [0.00532829 0.08186592 0.24890286 0.5754567  0.19666188]
 [0.00271543 0.00456113 0.11229482 0.01150204 0.0868677 ]
 [0.00266    0.00163947 0.05400185 0.00792101 0.07648491]]


# Broadcasting 
Explanation: Broadcasting allows element-wise operations between arrays of different shapes by automatically expanding the smaller array to match the larger one. 

In [140]:
import numpy as np

# Create a 3x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])  # 3x3 matrix


vector = np.array([1, 2, 3])  # Vector to add

# Add the vector to each row of the matrix using broadcasting
result = matrix + vector  # Broadcasting the vector across each row
print("Broadcasting Result:\n", result)


Broadcasting Result:
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [142]:
np.add(matrix, vector)

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [143]:
np.subtract(matrix, vector)

array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6]])

In [141]:
matrix - 3 

array([[-2, -1,  0],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [144]:
array1 = np.array([1, 2, 3])  # 1D array
array2 = np.array([[1], [2], [3]])  # 2D array (column vector)

array1 + array2  # Broadcasting for element-wise addition



array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [145]:
np.multiply(array1,array2)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [146]:
array1*array2

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [147]:
np.divide(array1,array2)

array([[1.        , 2.        , 3.        ],
       [0.5       , 1.        , 1.5       ],
       [0.33333333, 0.66666667, 1.        ]])

In [148]:
np.mod(array1,array2)

array([[0, 0, 0],
       [1, 0, 1],
       [1, 2, 0]])

# Linear Algebra and Matrix Operations

In [149]:

matrix1 = np.array([[1, 2],
                    [3, 4]])  # First matrix

matrix2 = np.array([[5, 6],
                    [7, 8]])  # Second matrix

# Compute the dot product
np.dot(matrix1, matrix2)  



array([[19, 22],
       [43, 50]])

In [156]:
np.matmul(matrix1,matrix2)

array([[19, 22],
       [43, 50]])

In [152]:

matrix = np.array([[1, 2],
                   [3, 4]])  # 2x2 matrix

np.linalg.inv(matrix)  # Inverse of the matrix
 


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [154]:

matrix = np.array([[1, 2],
                   [3, 4]])  # 2x2 matrix

# Compute eigenvalues and eigenvectors
np.linalg.eig(matrix)  # Eigenvalues and eigenvectors


EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [155]:
np.linalg.det(matrix)

np.float64(-2.0000000000000004)

In [157]:
array = np.array([10, 20, 30, 40, 50])  # Create a 1D array

# Randomly choose 3 elements from the array
np.random.choice(array, size=3, replace=False)  # No replacement



array([20, 40, 10])

In [158]:
 # Generate a 3x3 matrix of random integers between 0 and 100
np.random.randint(0, 100, size=(3, 3)) 

array([[67, 61, 14],
       [96,  4, 67],
       [11, 86, 77]], dtype=int32)

In [159]:

array = np.array([1, 2, 2, 3, 4, 4, 4, 5])

# Find unique elements
unique_elements = np.unique(array)  # Unique sorted elements
print("Unique Elements:", unique_elements)


Unique Elements: [1 2 3 4 5]


In [160]:
# Create two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

# Find intersection
intersection = np.intersect1d(array1, array2)  # Common elements
print("Intersection:", intersection)

# Find union
union = np.union1d(array1, array2)  # All unique elements from both arrays
print("Union:", union)

# Find set difference (elements in array1 not in array2)
set_difference = np.setdiff1d(array1, array2)  # Elements unique to array1
print("Set Difference (array1 - array2):", set_difference)

# Find set difference (elements in array2 not in array1)
set_difference2 = np.setdiff1d(array2, array1)  # Elements unique to array2
print("Set Difference (array2 - array1):", set_difference2)


Intersection: [4 5]
Union: [1 2 3 4 5 6 7 8]
Set Difference (array1 - array2): [1 2 3]
Set Difference (array2 - array1): [6 7 8]
