# Numpy
It has functions for working in domain of linear algebra, fourier transform, and matrices.
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

In [6]:
import numpy as np

In [7]:
# One way to initialize an array is using a Python sequence
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [8]:
# 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
# Create an array with 5 dimensions 
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# Array attributes

In [10]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [11]:
a.ndim

2

In [12]:
a.shape

(3, 4)

In [13]:
a.size

12

In [14]:
import math
a.size == math.prod(a.shape)

True

In [15]:
a.dtype

dtype('int64')

# Creating basic array

In [16]:
np.zeros(2)

array([0., 0.])

In [23]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [20]:
np.empty(2)

array([1., 1.])

In [21]:
np.arange(4)

array([0, 1, 2, 3])

In [24]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [25]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [26]:
x = np.ones(2, dtype=np.int64)

# Array Indexing, Reshaping and Slicing

In [58]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [59]:
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [60]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr[0, 1] #2nd element on 1st row:

np.int64(2)

In [61]:
arr[0]

array([1, 2, 3, 4, 5])

In [62]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr[0, 1, 2]

np.int64(6)

In [36]:
#  reshape an array
a = np.arange(6)
a.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [38]:
# np.newaxis will increase the dimensions of your array by one dimension when used once.
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
a2 = a[np.newaxis, :]
a2.shape

(6,)


(1, 6)

In [43]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
col_vector

(6, 1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [44]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [45]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [77]:
# ou do not have to specify an exact number for one of the dimensions in the reshape method. byPass -1 as the value
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
newarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [79]:
# Flattening array 
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
newarr

array([1, 2, 3, 4, 5, 6])

In [47]:
data = np.array([1, 2, 3])
data[1]

np.int64(2)

In [48]:
data[0:2]

array([1, 2])

In [49]:
data[1:]

array([2, 3])

In [64]:
# Return every other element from index 1 to index 5
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[1:5:2]

array([2, 4])

In [65]:
arr[::2]

array([1, 3, 5, 7])

In [53]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[a < 5] #print all of the values in the array that are less than 5

array([1, 2, 3, 4])

In [67]:
# From the second element, slice elements from index 1 to index 4 (not included)
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [55]:
divisible_by_2 = a[a%2==0]
divisible_by_2 

array([ 2,  4,  6,  8, 10, 12])

In [56]:
# use np.nonzero() to print the indices of elements that are
b = np.nonzero(a < 5)
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [68]:
# Change data type from float to integer by using 'i' as parameter valu
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [70]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [72]:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [73]:
# copy func
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [74]:
# view func
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [75]:
# to check if an array owns its own data
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


# Iterating Arrays

In [80]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [81]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [82]:
# Iterate on each scalar element of the 2-D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [83]:
# nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [85]:
# We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.
# NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].
arr = np.array([1, 2, 3])
# Iterate through the array as a string:
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [86]:
# Iterating With Different Step Size
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [88]:
# Enumerate on following 1D arrays elements
arr = np.array([5, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 5
(1,) 2
(2,) 3


In [89]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# NumPy Joining Array

In [90]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [93]:
# Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)
arr

array([[1, 4],
       [2, 5],
       [3, 6]])

In [94]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
# sorting
np.sort(arr)
# concatenate
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a, b))
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x, y))


array([[1, 2],
       [3, 4],
       [5, 6]])

In [97]:
# hstack() to stack along rows.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [99]:
# vstack()  to stack along columns.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
arr
Splitting Array

array([[1, 2, 3],
       [4, 5, 6]])

# Splitting Array

In [100]:
# Split the array in 3 parts
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [101]:
# Split Into Arrays
# array_split() method is an array containing each of the split as an array.
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [103]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
newarr

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]